finish 0x00-hello_world

diff --git a/0x00-hello_world/2-assembler b/0x00-hello_world/2-assembler
--- a/0x00-hello_world/2-assembler
+++ b/0x00-hello_world/2-assembler
@@ -1,8 +1,10 @@
-/*Write a script that generates the assembly code of a C code and save it in an output file.
+#!/bin/bash 
 
-The C file name will be saved in the variable $CFILE
-The output file should be named the same as the C file, but with the extension .s instead of .c.
-Example: if the C file is main.c, the output file should be main.s*/
+if [ -z "$CFILE" ]; then
+    echo "Error: CFILE env variable not set"
+    exit 1
+fi
 
-#!/bin/bash
-gcc -S $CFILE
+output_filename="${CFILE%.c}.s"
+
+gcc -S "$CFILE" -o "$output_filename"
